language: node_js
node_js:
  - "4.2.1"
script:
  - npm run lint
  - npm test
before_install:
  - npm install -g mocha eslint
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install rethinkdb

before_script:
    - rethinkdb --daemon
